# Generated by Django 2.2 on 2019-04-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='email',
            field=models.CharField(default='oriol@hackupc.com', max_length=255),
            preserve_default=False,
        ),
    ]
