# Generated by Django 2.2 on 2019-04-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_deployment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='region',
            field=models.CharField(default='us-central1-f', max_length=255),
            preserve_default=False,
        ),
    ]
